import {Metadata} from "next";
import "./page.css";
import Page from "./";

export const metadata: Metadata = {
  title: "日志",
  description: "Generated by create next app",
};
export default () => (<Page />);
// export default async function NotePage() {
//   // const tree = await api.note();
//   const tree = {data: [], code: 0, message: ''};
//   const parseTree = (data: NoteCategory[]): TreeNodeData[] => data.map(item => ({
//       label: item.name,
//       value: item.name,
//       nodeProps: item,
//       children: parseTree(item.children || []).concat(...(item.contents || []).map(content =>({
//           label: content.title,
//           value: content.title,
//           nodeProps: content,
//         } as TreeNodeData)))
//     }))
//   return (
//     <div id="note-page" className="container flex-auto mx-auto flex max-sm:flex-col">
//       <aside className="w-75 max-sm:w-full">
//         <Tree
//           data={parseTree(tree.data || [])}
//           levelOffset={23}
//           renderNode={ NoteTreeNode }
//           />
//       </aside>
//       <NoteEditor />
//     </div>
//   );
// }
